name: gg_router
description: Create nested routes. Sync app state and browser URL. Navigate absolutely and relatively. Animate route transitions. Save and restore state. Manage URI query parameters.
version: 2.0.0+dev.1
homepage: "https://github.com/inlavigo/gg_router"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  gg_value: ^1.1.0
  gg_once_per_cycle: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_async: ^1.1.0
  pedantic: ^1.9.2
  gg_easy_widget_test: ^1.0.0
